language: python
os: linux
dist: xenial
jobs:
  include:
  - name: Python 3.9 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.9.0
    - python -m pip install --upgrade pip
    env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
  - name: Python 3.8 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.8.0
    - python -m pip install --upgrade pip
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  - name: Python 3.7 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.0
    - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - name: Python 3.6 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.6.8
    - python -m pip install --upgrade pip
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
  - name: Python 2.7 (32bit) on Windows
    os: windows
    language: shell
    before_install:
    - choco install python2 --x86
    - python -m pip install --upgrade pip
    env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
  - name: Python 3.6 on Xenial Linux
    python: 3.6
install:
- pip install .
- pip list
before_script:
- python -c "import sys; print('Python verion ={}, sys.platform={}, is 64bit? = {}'.format(sys.version_info.major,
  sys.platform, (sys.maxsize > 2**32)))"
script:
- if [ $TRAVIS_OS_NAME != linux ]; then python ./test_imports.py; fi

